### ISSUE TITLE
Accessory clipped in the avatar, or scale broken at the legs (and Bounding Boxes?)

### ISSUE THREAD

**Issue by Lusiiky** [artieficial/ApplyAccessories#8]
Hi!

I've this problem with the [Latex Clothes for Rexouium](https://lamiho.gumroad.com/l/RexiLatexClothes) and legs that look broken.

By default, I get the same error as [Issue #7](https://github.com/artieficial/ApplyAccessories/issues/7):
![image](https://user-images.githubusercontent.com/29005043/162285234-1f3498d1-6e72-46b5-a603-3341a07ce19c.png)

But if I re-export in scale All FBX in Blender, I get this problem at the legs:
![image](https://user-images.githubusercontent.com/29005043/162284887-d5b703f0-ceb0-4309-b102-6460e7179025.png)

What it looks like by default:
![image](https://user-images.githubusercontent.com/29005043/162284883-65e3ac06-b8d7-45d4-81d4-ca46204833b0.png)

It works if I select "Don't Reuse Bones", but my goal in using ApplyAccessories is to avoid creating additional bones ^^'

And, by the way... wouldn't the Bouding Boxes be broken?

What can I do now..?

Thank you,
Lupsoris

**Comment by artieficial** [comment]
The issue is that if the bones don't line up 1:1 (aka the armature of the clothing is not the same as the armature of the model), you will get these kinds of issues. Certain other components can also lead to these kinds of issues. Unfortunately there isn't really a good way to resolve this. I'm going to start remaking apply accessories for physbones anyways, so hopefully that will fix this issue.
